name: app-env
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - imageio
  - jupyter
  - python=3.6
  - pandas
  - pip
  - numpy
  - scikit-learn
  - tensorflow-gpu=2.0.0
  - pip:
    - albumentations
    - google-cloud-storage
    - requests
    - rasterio