name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - imageio
  - jupyter
  - python=3.6
  - pandas
  - pip
  - numpy
  - scikit-learn
  - pip:
    - albumentations
    - google-cloud-storage
    - requests
    - rasterio
    - tensorflow-gpu==2.0.*